In [1]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')

document = "Almost before we knew it, we had left the ground. The unknown holds its grounds."
words = word_tokenize(document)

[nltk_data] Downloading package punkt to /home/azureuser/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [2]:
from gensim.test.utils import common_texts
from gensim.models import Word2Vec

model = Word2Vec(common_texts, size=100, window=5, min_count=1, workers=4)
model.save("word2vec.model")

In [3]:
model.train(words, total_examples=1, epochs=10)
vector = model.wv['computer']
vector

array([ 1.9774411e-03,  2.2904249e-03,  3.5071795e-04, -3.1516273e-03,
       -2.9400314e-04,  2.2245380e-03, -2.1723264e-03,  8.1412221e-04,
        2.9838423e-03,  4.3055606e-03, -2.6555124e-03,  1.5536546e-03,
       -4.3481276e-03, -8.1260572e-04,  3.3369529e-04, -4.8078173e-03,
       -4.8387242e-03, -3.7204607e-03,  3.3380019e-03, -3.5762258e-03,
        4.4796504e-03, -1.1373333e-03, -1.3311598e-03,  4.3706172e-03,
       -3.7637972e-03,  2.9590710e-03, -1.4322525e-03, -2.0373613e-03,
        4.8135367e-04, -2.7083571e-03,  2.5816900e-03, -3.4002620e-03,
        1.3443682e-03,  2.2372147e-03, -4.9781515e-03, -3.4560345e-03,
       -4.9998784e-03, -4.3443898e-03,  3.7806486e-03, -1.4412468e-03,
        3.4121003e-03,  2.2294878e-03,  5.6944572e-04,  1.9822600e-03,
        1.6988911e-03, -2.4962858e-03, -4.4961465e-03,  2.1202830e-03,
       -2.4118873e-03,  2.1624411e-03,  4.5080758e-03, -4.1531946e-04,
       -1.5294563e-03,  2.0263942e-03,  2.5381036e-03,  4.7241040e-03,
      

In [4]:
import numpy as np
dim = len(model.wv.vectors[0])
X = np.mean([model.wv[w] for w in words if w in model.wv] or [np.zeros(dim)], axis=0)
X

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
!wget http://nlp.stanford.edu/data/glove.6B.zip

--2020-04-27 07:01:34--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2020-04-27 07:01:34--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2020-04-27 07:01:35--  http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glove.6

In [6]:
!unzip glove.6B.zip

Archive:  glove.6B.zip
  inflating: glove.6B.50d.txt        
  inflating: glove.6B.100d.txt       
  inflating: glove.6B.200d.txt       
  inflating: glove.6B.300d.txt       


In [7]:
# download pre-trained dictionary from
# http://nlp.stanford.edu/data/glove.6B.zip
glove = {}
with open('glove.6B.100d.txt') as f:
    for line in f:
        word, coefs = line.split(maxsplit=1)
        coefs = np.fromstring(coefs, 'f', sep=' ')
        glove[word] = coefs

In [8]:
X = np.mean([glove[w] for w in words if w in glove] or [np.zeros(dim)], axis=0)
X

array([-0.02214288,  0.13323554,  0.42182863, -0.21241531, -0.24182692,
        0.10815544, -0.03382993,  0.21682625,  0.03170187, -0.01059731,
        0.3502211 ,  0.04510282,  0.43704262,  0.02482699,  0.14885199,
       -0.36020476,  0.12176169,  0.17731126, -0.49486253,  0.1112112 ,
        0.23972574,  0.01573795,  0.34841436, -0.07068056,  0.23785414,
       -0.05473639, -0.1512487 , -0.44285244,  0.02944756, -0.17841037,
       -0.05809868,  0.45183936, -0.09965506,  0.15062287, -0.04556245,
        0.15870292,  0.03015989,  0.31992587, -0.09309275, -0.24351062,
       -0.45814067, -0.28819084,  0.3615156 , -0.3137692 ,  0.00398818,
       -0.07265243,  0.31621274, -0.3198654 , -0.10144857, -0.6580169 ,
        0.13995756, -0.12287168,  0.18754566,  1.1996375 , -0.30202413,
       -2.5061686 , -0.18187013, -0.3012405 ,  1.5760057 ,  0.7284522 ,
       -0.16170405,  0.7219055 , -0.12360969,  0.14030151,  0.79812574,
       -0.18173608,  0.4080983 ,  0.28679436,  0.081286  , -0.05